Split the ulimit value from the kernel limit value.

diff --git a/etc/init.d/scytale b/etc/init.d/scytale
--- a/etc/init.d/scytale
+++ b/etc/init.d/scytale
@@ -19,15 +19,16 @@ RETVAL=0
 
 # Set limits here in addition to limits.conf
 #-------------------------------------------------------------------------------
+if [ -n "$KERNEL_OPEN_FILES" ]; then
+	sysctl -w fs.file-max=$KERNEL_OPEN_FILES > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "fs.file-max=$KERNEL_OPEN_FILES failed" && exit $RETVAL
+
+	sysctl -w fs.nr_open=$KERNEL_OPEN_FILES > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "fs.nr_open=$KERNEL_OPEN_FILES failed" && exit $RETVAL
+fi
 if [ -n "$ULIMIT_OPEN_FILES" ]; then
-	sysctl -w fs.file-max=$ULIMIT_OPEN_FILES > /dev/null
-	RETVAL=$?
-	[ $RETVAL -ne 0 ] && echo "fs.file-max=$ULIMIT_OPEN_FILES failed" && exit $RETVAL
-
-	sysctl -w fs.nr_open=$ULIMIT_OPEN_FILES > /dev/null
-	RETVAL=$?
-	[ $RETVAL -ne 0 ] && echo "fs.nr_open=$ULIMIT_OPEN_FILES failed" && exit $RETVAL
-
 	ulimit -n $ULIMIT_OPEN_FILES > /dev/null
 	RETVAL=$?
 	[ $RETVAL -ne 0 ] && echo "ulimit -n $ULIMIT_OPEN_FILES failed" && exit $RETVAL
@@ -47,6 +48,7 @@ if [ -n "$NET_IPV4_TCP_MAX_SYN_BACKLOG" ]; then
 	RETVAL=$?
 	[ $RETVAL -ne 0 ] && echo "net.ipv4.tcp_max_syn_backlog=$NET_IPV4_TCP_MAX_SYN_BACKLOG failed" && exit $RETVAL
 fi
+
 #-------------------------------------------------------------------------------
 
 start() {
@@ -59,8 +61,14 @@ start() {
 
 stop() {
 	echo -n $"Stopping scytale: "
+	pid=`cat /var/run/scytale.pid`
 	supervisorctl -c /etc/scytale/supervisord.conf shutdown > /dev/null
 	RETVAL=$?
+	while [[ 0 == ${?} ]]
+	do
+		sleep 1s
+		ps -p $pid > /dev/null
+	done
 	echo
 	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/scytale
 }
